// @flow
export const LIST_OPEN_TABLE_REQUEST = 'delivery/LIST_OPEN_TABLE_REQUEST';
export const LIST_QUEUED_TABLE_REQUEST = 'delivery/LIST_QUEUED_TABLE_REQUEST';
export const ACCEPT_QUEUED_REQUEST = 'delivery/ACCEPT_QUEUED_REQUEST';
export const DELETE_QUEUED_REQUEST = 'delivery/DELETE_QUEUED_REQUEST';
export const SECTION_CHANGE = 'delivery/SECTION_CHANGE';
export const LAYOUT_CHANGE = 'delivery/LAYOUT_CHANGE';
export const CLOSED_TABLE_SECTION_CHANGE = 'delivery/CLOSED_TABLE_SECTION_CHANGE';
export const LIST_DELIVERED_TABLE_REQUEST = 'delivery/LIST_CLOSED_TABLE_REQUEST';
