// @flow
export const LIST_OPEN_TABLE_REQUEST = 'table/LIST_OPEN_TABLE_REQUEST';
export const LIST_OPEN_TABLE_SUCCESS = 'table/LIST_OPEN_TABLE_SUCCESS';
export const LIST_OPEN_TABLE_FAILURE = 'table/LIST_OPEN_TABLE_FAILURE';
export const LIST_QUEUED_TABLE_REQUEST = 'table/LIST_QUEUED_TABLE_REQUEST';
export const LIST_QUEUED_TABLE_SUCCESS = 'table/LIST_QUEUED_TABLE_SUCCESS';
export const LIST_QUEUED_TABLE_FAILURE = 'table/LIST_QUEUED_TABLE_FAILURE';
export const APPROVE_ORDER_REQUEST = 'table/APPROVE_ORDER_REQUEST';
export const APPROVE_ORDER_SUCCESS = 'table/APPROVE_ORDER_SUCCESS';
export const APPROVE_ORDER_FAILURE = 'table/APPROVE_ORDER_FAILURE';
export const ACCEPT_QUEUED_REQUEST = 'table/ACCEPT_QUEUED_REQUEST';
export const DELETE_QUEUED_REQUEST = 'table/DELETE_QUEUED_REQUEST';
export const SECTION_CHANGE = 'table/SECTION_CHANGE';
export const LAYOUT_CHANGE = 'table/LAYOUT_CHANGE';
export const CLOSED_TABLE_SECTION_CHANGE = 'table/CLOSED_TABLE_SECTION_CHANGE';
export const LIST_CLOSED_TABLE_REQUEST = 'table/LIST_CLOSED_TABLE_REQUEST';
