// @flow
export const LIST_OPEN_TABLE_REQUEST = 'table/LIST_OPEN_TABLE_REQUEST';
export const LIST_QUEUED_TABLE_REQUEST = 'table/LIST_QUEUED_TABLE_REQUEST';
export const ACCEPT_QUEUED_REQUEST = 'table/ACCEPT_QUEUED_REQUEST';
export const DELETE_QUEUED_REQUEST = 'table/DELETE_QUEUED_REQUEST';
export const SECTION_CHANGE = 'table/SECTION_CHANGE';
export const LAYOUT_CHANGE = 'table/LAYOUT_CHANGE';
export const CLOSED_TABLE_SECTION_CHANGE = 'table/CLOSED_TABLE_SECTION_CHANGE';
export const LIST_CLOSED_TABLE_REQUEST = 'table/LIST_CLOSED_TABLE_REQUEST';
