// @flow
export const MENU_CREATE_REQUEST: string = 'menu/CREATE_REQUEST';
export const MENU_CREATE_SUCCESS: string = 'menu/CREATE_SUCCESS';
export const MENU_CREATE_FAILURE: string = 'menu/CREATE_FAILURE';

export const MENU_ADD_CATEGORY_REQUEST: string = 'menu/ADD_CATEGORY_REQUEST';
export const MENU_ADD_CATEGORY_SUCCESS: string = 'menu/ADD_CATEGORY_SUCCESS';
export const MENU_ADD_CATEGORY_FAILURE: string = 'menu/ADD_CATEGORY_FAILURE';

export const MENU_UPDATE_CATEGORY_REQUEST: string = 'menu/UPDATE_CATEGORY_REQUEST';
export const MENU_UPDATE_CATEGORY_SUCCESS: string = 'menu/UPDATE_CATEGORY_SUCCESS';
export const MENU_UPDATE_CATEGORY_FAILURE: string = 'menu/UPDATE_CATEGORY_FAILURE';

export const MENU_DELETE_CATEGORY_REQUEST: string = 'menu/DELETE_CATEGORY_REQUEST';
export const MENU_DELETE_CATEGORY_SUCCESS: string = 'menu/DELETE_CATEGORY_SUCCESS';
export const MENU_DELETE_CATEGORY_FAILURE: string = 'menu/DELETE_CATEGORY_FAILURE';

export const MENU_ADD_ITEM_REQUEST: string = 'menu/ADD_ITEM_REQUEST';
export const MENU_ADD_ITEM_SUCCESS: string = 'menu/ADD_ITEM_SUCCESS';
export const MENU_ADD_ITEM_FAILURE: string = 'menu/ADD_ITEM_FAILURE';

export const MENU_UPDATE_ITEM_REQUEST: string = 'menu/UPDATE_ITEM_REQUEST';
export const MENU_UPDATE_ITEM_SUCCESS: string = 'menu/UPDATE_ITEM_SUCCESS';
export const MENU_UPDATE_ITEM_FAILURE: string = 'menu/UPDATE_ITEM_FAILURE';

export const MENU_DELETE_ITEM_REQUEST: string = 'menu/DELETE_ITEM_REQUEST';
export const MENU_DELETE_ITEM_SUCCESS: string = 'menu/DELETE_ITEM_SUCCESS';
export const MENU_DELETE_ITEM_FAILURE: string = 'menu/DELETE_ITEM_FAILURE';

export const MENU_ADD_IMAGE_REQUEST: string = 'menu/MENU_ADD_IMAGE_REQUEST';
export const MENU_ADD_IMAGE_SUCCESS: string = 'menu/MENU_ADD_IMAGE_SUCCESS';
export const MENU_ADD_IMAGE_FAILURE: string = 'menu/MENU_ADD_IMAGE_FAILURE';

export const MENU_DELETE_IMAGE_REQUEST: string = 'menu/DELETE_IMAGE_REQUEST';
export const MENU_DELETE_IMAGE_SUCCESS: string = 'menu/DELETE_IMAGE_SUCCESS';
export const MENU_DELETE_IMAGE_FAILURE: string = 'menu/DELETE_IMAGE_FAILURE';
