// @flow
export const LOGIN_WITH_EMAIL_REQUEST = 'Login/LOGIN_WITH_EMAIL_REQUEST';
export const LOGIN_WITH_EMAIL_SUCCESS = 'Login/LOGIN_WITH_EMAIL_SUCCESS';
export const LOGIN_WITH_EMAIL_FAILURE = 'Login/LOGIN_WITH_EMAIL_FAILURE';

export const LOGIN_WITH_FACEBOOK_REQUEST = 'Login/LOGIN_WITH_FACEBOOK_REQUEST';
export const LOGIN_WITH_FACEBOOK_SUCCESS = 'Login/LOGIN_WITH_FACEBOOK_SUCCESS';
export const LOGIN_WITH_FACEBOOK_FAILURE = 'Login/LOGIN_WITH_FACEBOOK_FAILURE';

export type State = {
  user: UserType,
  error: string | null
};
