// @flow
export const LOGIN_WITH_EMAIL_REQUEST = 'Auth/LOGIN_WITH_EMAIL_REQUEST';
export const LOGIN_WITH_EMAIL_SUCCESS = 'Auth/LOGIN_WITH_EMAIL_SUCCESS';
export const LOGIN_WITH_EMAIL_FAILURE = 'Auth/LOGIN_WITH_EMAIL_FAILURE';

export const LOGIN_WITH_FACEBOOK_REQUEST = 'Auth/LOGIN_WITH_FACEBOOK_REQUEST';
export const LOGIN_WITH_FACEBOOK_SUCCESS = 'Auth/LOGIN_WITH_FACEBOOK_SUCCESS';
export const LOGIN_WITH_FACEBOOK_FAILURE = 'Auth/LOGIN_WITH_FACEBOOK_FAILURE';

export const USER_LOGOUT_REQUEST = 'Auth/USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'Auth/USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE = 'Auth/USER_LOGOUT_FAILURE';

export const SET_AUTHENTICATION_TOKEN = 'Auth/SET_AUTHENTICATION_TOKEN';
export const CLEAR_AUTHENTICATION_TOKEN = 'Auth/CLEAR_AUTHENTICATION_TOKEN';

export type State = {
  token: UserType,
  error: string | null
};
