// @flow
export const ADD_RESTAURANT_DETAIL_REQUEST: string = 'restaurant/ADD_RESTAURANT_DETAIL_REQUEST';
export const ADD_RESTAURANT_DETAIL_SUCCESS: string = 'restaurant/ADD_RESTAURANT_DETAIL_SUCCESS';
export const ADD_RESTAURANT_DETAIL_FAILURE: string = 'restaurant/ADD_RESTAURANT_DETAIL_FAILURE';

export const ADD_REMOVE_ITEM_QUANTITY_REQUEST: string = 'restaurant/ADD_REMOVE_ITEM_QUANTITY_REQUEST';
export const ADD_REMOVE_ITEM_QUANTITY_SUCCESS: string = 'restaurant/ADD_REMOVE_ITEM_QUANTITY_SUCCESS';
export const ADD_REMOVE_ITEM_QUANTITY_FAILURE: string = 'restaurant/ADD_REMOVE_ITEM_QUANTITY_FAILURE';

export const CHANGE_ITEM_RATING_REQUEST: string = 'restaurant/CHANGE_ITEM_RATING_REQUEST';
export const CHANGE_ITEM_RATING_SUCCESS: string = 'restaurant/CHANGE_ITEM_RATING_SUCCESS';
export const CHANGE_ITEM_RATING_FAILURE: string = 'restaurant/CHANGE_ITEM_RATING_FAILURE';

export const REMOVE_RESTAURANT_DETAIL_REQUEST: string = 'restaurant/REMOVE_RESTAURANT_DETAIL_REQUEST';
export const REMOVE_RESTAURANT_DETAIL_SUCCESS: string = 'restaurant/REMOVE_RESTAURANT_DETAIL_SUCCESS';
export const REMOVE_RESTAURANT_DETAIL_FAILURE: string = 'restaurant/REMOVE_RESTAURANT_DETAIL_FAILURE';

export const CLEAR_CART_DATA_REQUEST: string = 'restaurant/CLEAR_CART_DATA_REQUEST';
export const CLEAR_CART_DATA_SUCCESS: string = 'restaurant/CLEAR_CART_DATA_SUCCESS';
export const CLEAR_CART_DATA_FAILURE: string = 'restaurant/CLEAR_CART_DATA_FAILURE';
