// @flow
export const ADD_RESTAURANT_DETAIL_REQUEST: string = 'restaurant/ADD_RESTAURANT_DETAIL_REQUEST';
export const ADD_RESTAURANT_DETAIL_SUCCESS: string = 'restaurant/ADD_RESTAURANT_DETAIL_SUCCESS';
export const ADD_RESTAURANT_DETAIL_FAILURE: string = 'restaurant/ADD_RESTAURANT_DETAIL_FAILURE';

export const ADD_SELECTED_ITEM_REQUEST: string = 'restaurant/ADD_SELECTED_ITEM_REQUEST';
export const ADD_SELECTED_ITEM_SUCCESS: string = 'restaurant/ADD_SELECTED_ITEM_SUCCESS';
export const ADD_SELECTED_ITEM_FAILURE: string = 'restaurant/ADD_SELECTED_ITEM_FAILURE';
