// @flow
export const ADD_RESTAURANT_DETAIL_REQUEST: string = 'restaurant/ADD_RESTAURANT_DETAIL_REQUEST';
export const ADD_RESTAURANT_DETAIL_SUCCESS: string = 'restaurant/ADD_RESTAURANT_DETAIL_SUCCESS';
export const ADD_RESTAURANT_DETAIL_FAILURE: string = 'restaurant/ADD_RESTAURANT_DETAIL_FAILURE';

export const ADD_REMOVE_ITEM_QUANTITY_REQUEST: string = 'restaurant/ADD_REMOVE_ITEM_QUANTITY_REQUEST';
export const ADD_REMOVE_ITEM_QUANTITY_SUCCESS: string = 'restaurant/ADD_REMOVE_ITEM_QUANTITY_SUCCESS';
export const ADD_REMOVE_ITEM_QUANTITY_FAILURE: string = 'restaurant/ADD_REMOVE_ITEM_QUANTITY_FAILURE';

export const REMOVE_RESTAURANT_DETAIL_REQUEST: string = 'restaurant/REMOVE_RESTAURANT_DETAIL_REQUEST';
export const REMOVE_RESTAURANT_DETAIL_SUCCESS: string = 'restaurant/REMOVE_RESTAURANT_DETAIL_SUCCESS';
export const REMOVE_RESTAURANT_DETAIL_FAILURE: string = 'restaurant/REMOVE_RESTAURANT_DETAIL_FAILURE';

export const CLEAR_CART_DATA_REQUEST: string = 'restaurant/CLEAR_CART_DATA_REQUEST';
export const CLEAR_CART_DATA_SUCCESS: string = 'restaurant/CLEAR_CART_DATA_SUCCESS';
export const CLEAR_CART_DATA_FAILURE: string = 'restaurant/CLEAR_CART_DATA_FAILURE';

export const CREATE_ORDER_REQUEST: string = 'restaurant/CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS: string = 'restaurant/CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE: string = 'restaurant/CREATE_ORDER_FAILURE';

export const SHOW_LOADING_WHILE_ANIMATING_SCREEN = 'restaurant/SHOW_LOADING_WHILE_ANIMATING_SCREEN';
export const HIDE_LOADING_AFTER_SCREEN_ANIMATION = 'restaurant/HIDE_LOADING_AFTER_SCREEN_ANIMATION';
