export const GET_USER_OPEN_ORDER_REQUEST: string = 'userActivity/GET_USER_OPEN_ORDER_REQUEST';
export const GET_USER_OPEN_ORDER_SUCCESS: string = 'userActivity/GET_USER_OPEN_ORDER_SUCCESS';
export const GET_USER_OPEN_ORDER_FAILURE: string = 'userActivity/GET_USER_OPEN_ORDER_FAILURE';

export const MAKE_PAYMENT_AND_COMPLETE_ORDER_REQUEST: string = 'userActivity/MAKE_PAYMENT_AND_COMPLETE_ORDER_REQUEST';
export const MAKE_PAYMENT_AND_COMPLETE_ORDER_SUCCESS: stirng = 'userActivity/MAKE_PAYMENT_AND_COMPLETE_ORDER_SUCCESS';
export const MAKE_PAYMENT_AND_COMPLETE_ORDER_FAILURE: stirng = 'userActivity/MAKE_PAYMENT_AND_COMPLETE_ORDER_FAILURE';

export const CHANGE_STATUS_AND_CANCEL_ORDER_REQUEST: string = 'userActivity/CHANGE_STATUS_AND_CANCEL_ORDER_REQUEST';
export const CHANGE_STATUS_AND_CANCEL_ORDER_SUCCESS: string = 'userActivity/CHANGE_STATUS_AND_CANCEL_ORDER_SUCCESS';
export const CHANGE_STATUS_AND_CANCEL_ORDER_FAILURE: string = 'userActivity/CHANGE_STATUS_AND_CANCEL_ORDER_FAILURE';
