export const GET_USER_COMPLETED_ORDERS_REQUEST: string = 'userHistory/GET_USER_COMPLETED_ORDERS_REQUEST';
export const GET_USER_COMPLETED_ORDERS_SUCCESS: string = 'userHistory/GET_USER_COMPLETED_ORDERS_SUCCESS';
export const GET_USER_COMPLETED_ORDERS_FAILURE: string = 'userHistory/GET_USER_COMPLETED_ORDERS_FAILURE';
