// @flow
export const TOGGLE_FILTER_REQUEST: string = 'explore/TOGGLE_FILTER_REQUEST';
export const TOGGLE_FILTER_SUCCESS: string = 'explore/TOGGLE_FILTER_SUCCESS';
export const TOGGLE_FILTER_FAILURE: string = 'explore/TOGGLE_FILTER_FAILURE';

export const LIST_VENDORS_REQUEST: string = 'explore/LIST_VENDORS_REQUEST';
export const LIST_VENDORS_SUCCESS: string = 'explore/LIST_VENDORS_SUCCESS';
export const LIST_VENDORS_FAILURE: string = 'explore/LIST_VENDORS_FAILURE';

export const UPDATE_DISTANCE_REQUEST: string = 'explore/UPDATE_DISTANCE_REQUEST';
export const UPDATE_DISTANCE_SUCCESS: string = 'explore/UPDATE_DISTANCE_SUCCESS';
export const UPDATE_DISTANCE_FAILURE: string = 'explore/UPDATE_DISTANCE_FAILURE';

export const UPDATE_PRICE_FILTER_REQUEST: string = 'explore/UPDATE_PRICE_FILTER_REQUEST';
export const UPDATE_PRICE_FILTER_SUCCESS: string = 'explore/UPDATE_PRICE_FILTER_SUCCESS';
export const UPDATE_PRICE_FILTER_FAILURE: string = 'explore/UPDATE_PRICE_FILTER_FAILURE';

export const DISABLE_VENDOR_LIST_ITEM: string = 'explore/DISABLE_VENDOR_LIST_ITEM';

export const GET_USER_CURRENT_LOCATION_REQUEST: string = 'explore/GET_USER_CURRENT_LOCATION_REQUEST';
export const GET_USER_CURRENT_LOCATION_SUCCESS: string = 'explore/GET_USER_CURRENT_LOCATION_SUCCESS';
export const GET_USER_CURRENT_LOCATION_FAILURE: stirng = 'explore/GET_USER_CURRENT_LOCATION_FAILURE';
